name: Build VyOS LTS

on:
  workflow_dispatch  

env:
  RELEASE_VERSION: '1.3.2'
  RELEASE_COMMIT_HASH: '7ce865118886358efde71a5d3782d21063b01a22'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build iso
      run: |
        mkdir -p vyos-build
        cd vyos-build
        git init
        git remote add origin https://github.com/vyos/vyos-build.git
        git fetch --depth 1 origin "$RELEASE_COMMIT_HASH"
        git reset --hard FETCH_HEAD
        docker build -t vyos/vyos-build:equuleus docker
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:equuleus bash -c './configure --architecture amd64 --build-type release --version "$RELEASE_VERSION" && sudo make iso'

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        tag: ${{ env.RELEASE_VERSION }}
        overwrite: true
        file_glob: true
  
  
